### ISSUE TITLE
when does the blade treesitter start?

### ISSUE THREAD

**Issue by rainbow-bash** [johnsci911/nvim-ide#3]
hello im trying to get teh blade treesitter to work in my config but i cant quite decipher it is just the blade dir and thats it? no need to install it as a plugin, i am so sorry for asking over here but im not finding something like this anywhere:(

**Comment by johnsci911** [comment]
Please see this guide here -> https://github.com/EmranMR/tree-sitter-blade/discussions/19#discussion-5400675

I think you should run `:TSInstall blade`. At least on my experience I forgot that one
